spring:
  jpa:
    hibernate:
      ddl-auto: create-drop

    generate-ddl: true
    show-sql: true
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect

logging:
  level:
    org:
      springframework:
        web: DEBUG
      hibernate:
        sql: DEBUG
    jpa: DEBUG